@startuml
package "menu" {
    package "main" {

        class MainActivity {
            binding: ActivityMainBinding
            onCreate(Bundle?): Unit
            onCreateOptionsMenu(Menu): Boolean
            onDestroy(): Unit
        }
    }
}
@enduml