@startuml
'comment

' packages
package "menu" {

'    class EntryActivity {
'    		LOG_TAG: String!
'        binding: ActivityEntryBinding
'    ' TODO should "Unit" be omitted? it basically means "void"
'        onCreate(Bundle?): Unit
'        onDestroy(): Unit
'    }

    package "main" {

        class MainActivity {
            LOG_TAG: String!
            binding: ActivityMainBinding
            mediaBrowser: MediaBrowserCompat
            //connectionCallbacks//
            //controllerCallbacks//
            onCreate(Bundle?): Unit
            onCreateOptionsMenu(Menu): Boolean
            buildTransportProtocols(): Unit
            getMainMediaController(): MediaControllerCompat
            onStart(): Unit
            onStop(): Unit
            onDestroy(): Unit
        }
        
        class connectionCallbacks <<(O,orange)MediaBrowserCompat.ConnectionCallback()>> {
        		onConnected(): Unit
        		onConnectionSuspended(): Unit
        		onConnectionFailed(): Unit
        }
        
        class controllerCallbacks <<(O,orange)MediaController.Callback()>> {
        		onMetaDataChanged(MediaMetadataCompat?): Unit
        		onPlaybackStateChanged(PlaybackStateCompat?): Unit
        		onSessionDestroyed(): Unit
        }
        
        note "'O' for 'Object'" as N2
        connectionCallbacks .. N2
        N2 .. controllerCallbacks

        class MainFragment {
            binding: FragmentMainBinding
            onCreateView(LayoutInflater, ViewGroup?, Bundle?): View
            onViewCreated(View, Bundle?): Unit
            onDestroy(): Unit
        }
    }

    package "sub" {
        package "audio" {

            class AudioFragment {
            		LOG_TAG: String!
                binding: FragmentAudioBinding
                audioAdapter: AudioAdapter
                audioList: List<Audio>
                mediaController: MediaControllerCompat
                AudioFragment()
                onAttach(Context): Unit
                onCreateView(LayoutInflater, ViewGroup?, Bundle?): View
                onViewCreated(View, Bundle?): Unit
                onAudioClickListener(Int): Unit
                onStart(): Unit
                onResume(): Unit
                onStop(): Unit
                onDestroy(): Unit
            }

            class AudioAdapter {
                context: AudioFragment
                audioList: List<Audio>
                audioListener: AudioListener
                AudioAdapter(AudioFragment, List<Audio>, AudioListener)
                onCreateViewHolder(ViewGroup, Int): AudioAdapter.AudioViewHolder
                onBindViewHolder(AudioAdapter.AudioViewHolder, Int): Unit
                getItemCount(): Int
            }

            class AudioViewHolder {
                textView: TextView
                currentAudio: Audio?
            ' TODO what to do with this pain in the ass?
                <class initialiser>
                AudioViewHolder(View)
                bind(Audio): Unit
            }

            class Audio {
                id: Long
                name: String
                audio: Int?
                Audio(Long, String, Int?)
            }

            interface AudioListener {
                onAudioClickListener(Int): Unit
            }
            'TODO how to handle "Audios.kt"
            class Audios <<(F,orchid)>> {
                audioList(): List<Audio>

            }
            note right: "F" for "File"
        }
    }
}

' dependencies
    AudioListener <|-- AudioFragment
    AudioAdapter +-- AudioViewHolder
    MainActivity +-- connectionCallbacks
    MainActivity +-- controllerCallbacks

' output layout
		controllerCallbacks -[hidden]> connectionCallbacks
    main -[hidden]> sub
    Audio-[hidden]-> Audios
    AudioAdapter-[hidden]-Audio
@enduml
